<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>R2Game</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\R2Engine.Runtime\R2Engine.Runtime.csproj" />
    <ProjectReference Include="..\R2Engine.Desktop\R2Engine.Desktop.csproj" />
  </ItemGroup>
</Project>
