using System.Text;
using R2Engine.Editor;
using R2Engine.Editor.Scene;
using R2Engine.Runtime.Platform;

static void Check(bool ok, string message) { if (!ok) throw new Exception(message); }
RuntimePlatform.Configure(new DesktopPlatformServices("Animator test", () => {}));
string root = AssetDatabase.ProjectRoot;
string output = Path.GetFullPath(Path.Combine(root, "..", "Builds", "AnimatorTest-" + Guid.NewGuid().ToString("N")));
Directory.CreateDirectory(output);
Scene scene = SceneSerializer.Load(Path.Combine(root, "Scenes", "scene1.r2scene"));
var man = scene.GameObjects.First(o => o.Name == "Munch" || o.Name.Contains("low poly man"));
var animator = man.GetComponent<Animator>()!;
var original = AnimatorController.Load(AssetDatabase.ToAbsolutePath(animator.ControllerPath));
var idle = original.States[0];
var controller = new AnimatorController { DefaultState = "Celebrate", States = new() {
    new AnimatorState { Name = "Other", AnimationPath = idle.AnimationPath, AnimationTake = idle.AnimationTake },
    new AnimatorState { Name = "Celebrate", AnimationPath = idle.AnimationPath, AnimationTake = idle.AnimationTake, Loop = false, Speed = .5f }
}};
controller.Transitions.Add(new AnimatorTransition { From = "Celebrate", To = "Other", Condition = AnimatorCondition.Finished, BlendDuration = .35f });
controller.Transitions.Add(new AnimatorTransition { From = "Celebrate", To = "Celebrate", Condition = AnimatorCondition.Finished, BlendDuration = 0 });
controller.Parameters.Add(new AnimatorParameter { Name = "Go", Type = AnimatorParameterType.Boolean, BoolValue = true });
controller.Parameters.Add(new AnimatorParameter { Name = "Attack", Type = AnimatorParameterType.Trigger });
controller.Transitions.Add(new AnimatorTransition { From = "Other", To = "Celebrate", Condition = AnimatorCondition.IsTrue, Parameter = "Go", BlendDuration = .2f });
controller.Transitions.Add(new AnimatorTransition { From = "Other", To = "Celebrate", Condition = AnimatorCondition.Triggered, Parameter = "Attack" });
string controllerPath = Path.Combine(output, "Custom.r2controller");
File.WriteAllText(controllerPath, System.Text.Json.JsonSerializer.Serialize(controller));
animator.ControllerPath = controllerPath;
animator.PlayOnStart = true;
var second = scene.CreateGameObject("Stopped copy");
second.AddComponent<MeshRenderer>().MeshPath = man.GetComponent<MeshRenderer>()!.MeshPath;
var stopped = second.AddComponent<Animator>(); stopped.ControllerPath = controllerPath; stopped.PlayOnStart = false;
Check(Ps2AnimationPackageExporter.MeshKey(second.GetComponent<MeshRenderer>()!) == Ps2AnimationPackageExporter.MeshKey(man.GetComponent<MeshRenderer>()!), "Identical controllers share baked data");
string variantPath = Path.Combine(output, "Faster.r2controller");
controller.States[1].Speed = 2;
File.WriteAllText(variantPath, System.Text.Json.JsonSerializer.Serialize(controller));
stopped.ControllerPath = variantPath;
Check(Ps2AnimationPackageExporter.MeshKey(second.GetComponent<MeshRenderer>()!) != Ps2AnimationPackageExporter.MeshKey(man.GetComponent<MeshRenderer>()!), "Different playback settings cannot collide in the mesh cache");
stopped.ControllerPath = controllerPath;
string scenePath = Path.Combine(output, "Test.r2scene");
// Remove unrelated trigger/button destinations from this isolated fixture.
foreach (var o in scene.GameObjects) {
    o.RemoveComponent<AnimatorTriggerZone>();
    o.RemoveComponent<Interactable>();
    if (o.GetComponent<ScriptComponent>() is {} script) script.FieldValues.Remove("SceneName");
    if (o.GetComponent<UIButton>() is {} button) button.Action = UIButtonAction.None;
}
File.WriteAllText(scenePath, SceneSerializer.Serialize(scene));
var assets = BuildAssetCollector.Collect(new[] {scenePath});
MeshPackageExporter.Export(assets, output);
Ps2AnimationPackageExporter.Export(new[] {scenePath}, output);
ScenePackageExporter.Export(new[] {scenePath}, output, new ProjectSettings());
string key = Ps2AnimationPackageExporter.MeshKey(man.GetComponent<MeshRenderer>()!);
byte[] animation = File.ReadAllBytes(Path.Combine(output, "R2Data", "Meshes", Path.ChangeExtension(key, ".r2anim")));
Check(BitConverter.ToUInt32(animation, 4) == 5, "R2AN v5");
int metadata = 16 + (int)BitConverter.ToUInt32(animation, 12)*36;
Check(BitConverter.ToUInt32(animation, metadata) == 2 && BitConverter.ToUInt32(animation, metadata+4) == 4, "Parameter and transition counts");
Check(BitConverter.ToUInt32(animation, metadata+8) == 2 && BitConverter.ToSingle(animation, metadata+12) == 1, "Boolean default exported");
Check(System.Text.Encoding.UTF8.GetString(animation, metadata+16, 2) == "Go", "Parameter name exported");
int edges = metadata+8+2*72;
Check(BitConverter.ToUInt32(animation, edges+2*24+8) == 0 && BitConverter.ToUInt32(animation, edges+2*24+12) == 0, "Boolean condition references parameter index");
Check(BitConverter.ToUInt32(animation, edges+3*24+8) == 5 && BitConverter.ToUInt32(animation, edges+3*24+12) == 1, "Trigger preserves authored order");
Check(BitConverter.ToUInt32(animation, 16) == uint.MaxValue, "Arbitrary state name exported");
Check(BitConverter.ToUInt32(animation, 36) == 0 && BitConverter.ToSingle(animation, 40) == .5f, "Default-state ordering, nonlooping and speed");
Check(BitConverter.ToUInt32(animation, 44) == 1 && BitConverter.ToSingle(animation, 48) == .35f, "First Finished transition and authored blend exported with reordered target index");
Check(BitConverter.ToUInt32(animation, 16+36+28) == uint.MaxValue, "No transition sentinel for destination state");
int first = (int)BitConverter.ToUInt32(animation, 32), vertices = (int)BitConverter.ToUInt32(animation, 8);
Check(!animation.AsSpan(first, vertices*24).SequenceEqual(animation.AsSpan(first+vertices*24, vertices*24)), "Baked clip actually moves");
byte[] cooked = File.ReadAllBytes(Path.Combine(output, "R2Data", "Scenes", "Test.r2scene"));
int count = (int)BitConverter.ToUInt32(cooked, 16), offset = cooked.Length-count*8;
var renderers = scene.GameObjects.Where(o => o.IsActiveInHierarchy && o.GetComponent<MeshRenderer>() != null).ToArray();
Check(BitConverter.ToUInt32(cooked, offset + Array.IndexOf(renderers, man)*8) == 3, "NPC starts playing");
Check(BitConverter.ToUInt32(cooked, offset + Array.IndexOf(renderers, second)*8) == 1, "Second instance stays stopped");
Check(BitConverter.ToUInt32(cooked,4) == 24, "Scene playback records version");
Console.WriteLine("PASS: arbitrary default state, loop/speed metadata, moving baked frames, shared data and independent PlayOnStart records.");
Console.WriteLine(output);
controller.States[1].Speed = .5f;
controller.Transitions[0].BlendDuration = .8f;
File.WriteAllText(controllerPath, System.Text.Json.JsonSerializer.Serialize(controller));
Check(Ps2AnimationPackageExporter.MeshKey(man.GetComponent<MeshRenderer>()!) != key, "Transition changes invalidate baked animation key");
// A zone is independent of renderers: invisible geometry still exports.
var zoneObject = scene.CreateGameObject("Wave Zone");
zoneObject.Transform.Position = new System.Numerics.Vector3(2,3,4);
zoneObject.AddComponent<BoxCollider>().IsTrigger = true;
var zone = zoneObject.AddComponent<AnimatorTriggerZone>(); zone.TargetAnimator = man.Name; zone.TriggerName = "Attack";
File.WriteAllText(scenePath, SceneSerializer.Serialize(scene));
var roundTrip = SceneSerializer.Deserialize(File.ReadAllText(scenePath)).GameObjects.First(o => o.Name == "Wave Zone");
Check(roundTrip.GetComponent<AnimatorTriggerZone>()?.TargetAnimator == man.Name, "Zone reference survives serialization");
ScenePackageExporter.Export(new[] {scenePath}, output, new ProjectSettings());
byte[] withZone = File.ReadAllBytes(Path.Combine(output,"R2Data","Scenes","Test.r2scene"));
int zoneOffset = withZone.Length-count*8-100;
Check(BitConverter.ToUInt32(withZone,4)==25 && BitConverter.ToUInt32(withZone,zoneOffset)==1, "v25 standalone zone count");
Check(BitConverter.ToInt32(withZone,zoneOffset+4)==Array.IndexOf(renderers,man), "Zone targets correct animated instance");
Check(BitConverter.ToSingle(withZone,zoneOffset+8)==2 && Encoding.UTF8.GetString(withZone,zoneOffset+32,6)=="Attack", "Zone bounds and trigger exported");
var contactScene = new Scene("Zone entry test");
var npc = contactScene.CreateGameObject("NPC"); var npcAnimator = npc.AddComponent<Animator>();
var volume = contactScene.CreateGameObject("Zone"); volume.AddComponent<BoxCollider>().IsTrigger=true;
var action = volume.AddComponent<AnimatorTriggerZone>(); action.TargetAnimator="NPC"; action.TriggerName="Wave";
var visitor = contactScene.CreateGameObject("Player"); visitor.AddComponent<PlayerController>(); visitor.AddComponent<CapsuleCollider>();
var collisions = new CollisionSystem();
var triggers = (HashSet<string>)typeof(Animator).GetField("_triggers",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic)!.GetValue(npcAnimator)!;
collisions.Update(contactScene); Check(triggers.Contains("Wave"), "Entry fires");
npcAnimator.ResetTrigger("Wave"); collisions.Update(contactScene); Check(!triggers.Contains("Wave"), "Stay does not repeat");
visitor.Transform.Position = new System.Numerics.Vector3(20,0,0); collisions.Update(contactScene);
visitor.Transform.Position = System.Numerics.Vector3.Zero; collisions.Update(contactScene); Check(triggers.Contains("Wave"), "Reentry rearms");
Console.WriteLine("PASS: invisible zone serialization/cooking and desktop entry/stay/reentry.");
var dialogueObject=scene.CreateGameObject("TestDialogue"); dialogueObject.AddComponent<Canvas>(); dialogueObject.AddComponent<UIText>().Text="Hello";
var interaction=man.AddComponent<Interactable>(); interaction.TargetCanvas="TestDialogue"; interaction.Prompt="Talk";
var interactionBox=man.AddComponent<BoxCollider>(); interactionBox.IsTrigger=true; interactionBox.Size=new System.Numerics.Vector3(4,3,4);
File.WriteAllText(scenePath,SceneSerializer.Serialize(scene));
Check(SceneSerializer.Deserialize(File.ReadAllText(scenePath)).GameObjects.First(o=>o.Name==man.Name).GetComponent<Interactable>()?.TargetCanvas=="TestDialogue","Interaction save/load");
ScenePackageExporter.Export(new[]{scenePath},output,new ProjectSettings());
byte[] interactive=File.ReadAllBytes(Path.Combine(output,"R2Data","Scenes","Test.r2scene"));
  int interactOffset=interactive.Length-count*8-620;
  Check(BitConverter.ToUInt32(interactive,4)==27 && BitConverter.ToUInt32(interactive,interactOffset)==1,"Interaction v27 count");
Check(BitConverter.ToUInt32(interactive,interactOffset+32)==0 && Encoding.UTF8.GetString(interactive,interactOffset+36,8)=="X - Talk","Cross binding and prompt export");
var ui=contactScene.CreateGameObject("Dialogue"); var dialogue=ui.AddComponent<Canvas>(); var dialogueText=ui.AddComponent<UIText>();
var talk=npc.AddComponent<Interactable>(); talk.TargetCanvas="Dialogue"; talk.DialoguePages="Hello there\nSee you later";
var talkBox=npc.AddComponent<BoxCollider>(); talkBox.IsTrigger=true; talkBox.Size=new System.Numerics.Vector3(4,3,4);
RuntimeInput.Configure(Array.Empty<InputActionBinding>());
RuntimeInput.BeginFrame(); RuntimeInput.SetKey(RuntimeKey.E,false);
collisions.Update(contactScene);
Check(Interactable.FindNearest(contactScene)==talk,"Nearby NPC selected");
Interactable.Update(contactScene);
Check(contactScene.GameObjects.Any(o=>o.GetComponent<Canvas>() is {IsInteractionPrompt:true,IsVisible:true}),"Prompt appears");
  RuntimeInput.BeginFrame(); RuntimeInput.SetKey(RuntimeKey.E,true); Interactable.Update(contactScene);
  Check(dialogue.IsVisible && RuntimeInput.InteractionConsumed,"Interaction opens dialogue and consumes press");
  Check(Interactable.ActiveCanvas(contactScene)==dialogue,"Interaction remains active while dialogue is visible");
  Check(dialogueText.Text=="Hello there","First dialogue page appears");
  Check(Interactable.FindNearest(contactScene)==null,"No new interaction while dialogue open");
  var controllerToLock=visitor.GetComponent<PlayerController>()!;
  controllerToLock.SuspendMovement();
  RuntimeInput.BeginFrame(); RuntimeInput.SetKey(RuntimeKey.E,false); Interactable.Update(contactScene);
  RuntimeInput.BeginFrame(); RuntimeInput.SetKey(RuntimeKey.E,true); Interactable.Update(contactScene);
  Check(dialogue.IsVisible && dialogueText.Text=="See you later","Interaction action advances dialogue");
  RuntimeInput.BeginFrame(); RuntimeInput.SetKey(RuntimeKey.E,false); Interactable.Update(contactScene);
  RuntimeInput.BeginFrame(); RuntimeInput.SetKey(RuntimeKey.E,true); Interactable.Update(contactScene);
  Check(!dialogue.IsVisible && Interactable.ActiveCanvas(contactScene)==null,"Final dialogue page releases interaction");
RuntimeInput.BeginFrame(); Interactable.Update(contactScene); Check(!dialogue.IsVisible,"Held input does not reopen");
visitor.Transform.Position=new System.Numerics.Vector3(30,0,0);
collisions.Update(contactScene);
Check(Interactable.FindNearest(contactScene)==null,"Out of range hides interaction");
Console.WriteLine("PASS: interaction serialization/cooking, trigger entry/exit, prompt, opening, input consumption and cancel.");
controller.Transitions[0].To = "Missing state";
File.WriteAllText(controllerPath, System.Text.Json.JsonSerializer.Serialize(controller));
try { Ps2AnimationPackageExporter.Export(new[] {scenePath}, output); throw new Exception("Invalid target was accepted"); }
catch (InvalidOperationException e) { Check(e.Message.Contains("missing state"), "Broken transition reports a clear cook error"); }
Console.WriteLine("PASS: Finished target/order/blend export, cache invalidation and missing-state validation.");
