using System.Numerics;
using R2Engine.Editor;
using R2Engine.Editor.Scene;
static void Check(bool v,string message){if(!v)throw new Exception(message);}
Check(typeof(SlidingDoor).Assembly==typeof(Component).Assembly,"Door component belongs to shared runtime, not editor-only assembly");
var scene=new Scene("DoorTest");var root=scene.CreateGameObject("Doorway");SlidingDoor.BuildDoorway(root);
var panel=scene.GameObjects.Single(o=>o.GetComponent<SlidingDoor>()!=null);var door=panel.GetComponent<SlidingDoor>()!;
var player=scene.CreateGameObject("Player");player.AddComponent<PlayerController>();player.AddComponent<MeshRenderer>();player.AddComponent<CapsuleCollider>();player.Transform.Position=new(0,0,2);
Check(scene.GameObjects.Count==6 && panel.GetComponent<BoxCollider>() is {IsTrigger:false},"Ready-made doorway and solid panel");
string original=SceneSerializer.Serialize(scene);
Check(SlidingDoor.FindNearest(scene)==door,"Near player sees door");
player.Transform.Position=new(0,0,20);Check(SlidingDoor.FindNearest(scene)==null,"Out of range");player.Transform.Position=new(0,0,2);
RuntimeInput.Clear();RuntimeInput.Configure(new[]{new InputActionBinding{Name="Interact",Type=InputActionType.Button,Primary=RuntimeKey.E,Secondary=RuntimeKey.E,ControllerButton=0}});
RuntimeInput.BeginFrame();SlidingDoor.Update(scene,.1f);Check(!door.Opening,"No automatic proximity opening");
Check(scene.GameObjects.Any(o=>o.GetComponent<UIText>()?.Text.Contains("Open")==true),"Open prompt exists");
var camera=scene.CreateGameObject("Camera");var collision=new CollisionSystem();
float blocked=collision.CameraSweep(scene,player,camera,new(0,1,-2),new(0,1,2),.1f);Check(blocked<2,"Closed door blocks passage ray");
for(int i=0;i<40;i++)collision.Move(player,new(0,0,-.1f),scene);
Check(player.Transform.WorldPosition.Z>0,"Player cannot walk through closed panel");player.Transform.Position=new(0,0,2);
RuntimeInput.BeginFrame();RuntimeInput.SetKey(RuntimeKey.E,true);SlidingDoor.Update(scene,.1f);
Check(door.Opening && RuntimeInput.InteractionConsumed,"Interact opens and consumes jump input");
float paused=door.Progress;door.Tick(0);Check(door.Progress==paused,"Pause freezes travel");
for(int i=0;i<100;i++)door.Tick(.1f);
Check(MathF.Abs(door.Progress-door.Lift)<.001f && MathF.Abs(panel.Transform.WorldPosition.Y-4.8f)<.001f,"Stops at full lift");
Check(collision.CameraSweep(scene,player,camera,new(0,1,-2),new(0,1,2),.1f)>3.9f,"Open collider clears passage");
for(int i=0;i<40;i++)collision.Move(player,new(0,0,-.1f),scene);
Check(player.Transform.WorldPosition.Z < -1.9f,"Player walks through open doorway");
Check(SlidingDoor.FindNearest(scene)==null,"Open door no longer prompts");
var reset=SceneSerializer.Deserialize(original);var resetDoor=reset.GameObjects.Select(o=>o.GetComponent<SlidingDoor>()).Single(d=>d!=null)!;
Check(!resetDoor.Opening && resetDoor.Progress==0 && resetDoor.Lift==door.Lift,"Reload resets runtime state and retains settings");
var menu=reset.CreateGameObject("Pause").AddComponent<Canvas>();menu.IsVisible=true;menu.PauseGameplayWhenVisible=true;
Check(SlidingDoor.FindNearest(reset)==null,"Pause menu suppresses interaction");
string scratch=Path.Combine(Path.GetTempPath(),"r2-door-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(scratch);
string path=Path.Combine(scratch,"DoorTest.r2scene");File.WriteAllText(path,original);
ScenePackageExporter.Export(new[]{path},Path.Combine(scratch,"build"),new ProjectSettings());
byte[] bytes=File.ReadAllBytes(Path.Combine(scratch,"build/R2Data/Scenes/DoorTest.r2scene"));
Check(BitConverter.ToInt32(bytes,4)==44,"Door scene v44");int count=BitConverter.ToInt32(bytes,16);Check(count==5,"Four doorway meshes and player");
int block=bytes.Length-count*92-36;Check(BitConverter.ToUInt32(bytes,block)==1,"One door record before script tail");
Check(BitConverter.ToUInt32(bytes,block+4)==3 && BitConverter.ToUInt32(bytes,block+8)==0,"Door source and Cross mapping");
Check(BitConverter.ToSingle(bytes,block+12)==3.3f && BitConverter.ToSingle(bytes,block+16)==2 && BitConverter.ToSingle(bytes,block+20)==3,"Door settings layout");
var bad=SceneSerializer.Deserialize(original);bad.GameObjects.Select(o=>o.GetComponent<SlidingDoor>()).Single(d=>d!=null)!.Speed=0;File.WriteAllText(path,SceneSerializer.Serialize(bad));
bool rejected=false;try{ScenePackageExporter.Export(new[]{path},Path.Combine(scratch,"bad"),new ProjectSettings());}catch(InvalidOperationException){rejected=true;}Check(rejected,"Bad speed rejected");
Console.WriteLine("PASS: doorway creation, range, prompt, consumed input, movement, pause, solid collision clearance, reload, v44 export and invalid settings");
Console.WriteLine("Fixture: "+Path.Combine(scratch,"build/R2Data/Scenes/DoorTest.r2scene"));
